export const POSTS_TYPES = {
  GET_ALL_POSTS_REQUEST: "POSTS_TYPES.GET_ALL_POSTS_REQUEST",
  GET_ALL_POSTS_SUCCESS: "POSTS_TYPES.GET_ALL_POSTS_SUCCESS",
  GET_POST_REQUEST: "POSTS_TYPES.GET_POST_REQUEST",
  GET_POST_SUUCESS: "POSTS_TYPES.GET_POST_SUUCESS",
  GET_POST_FAILED: "POSTS_TYPES.GET_POST_FAILED",
  CREATE_POST_REQUEST: "POSTS_TYPES.CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "POSTS_TYPES.CREATE_POST_SUCCESS",
}